### ISSUE TITLE
Final group capstone - Book an Appointment

### ISSUE THREAD

**Issue by sentayhu19** [sentayhu19/Book-an-appointment-back-end#18]
**Final group capstone - Book an Appointment**

Group Members :

1. Solomon Hagan @Achilles-Dev 
2. Debas Gebreslasie @Debas-31 
3. Ayoub Chahir @AyoubMs 
4. Sentayhu Berhanu @sentayhu19 

[Project Link](https://github.com/sentayhu19/Book-an-appointment-back-end/projects/1)
![kanban](https://user-images.githubusercontent.com/77745775/184105254-444d5425-98de-4e7e-b920-79e09d1032ea.png)

**Comment by MuriloRoque** [comment]
Hi @sentayhu19, @Achilles-Dev, @Debas-31, @AyoubMs,

Good job so far!
There are some issues that you still need to work on but you are almost there!

## Suggested changes

- [x] Please put a screenshot of your Kanban board to this issue's description, as it says in the requirements.

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by MuriloRoque** [comment]
Hi @Achilles-Dev, @sentayhu19, @Debas-31, @AyoubMs,

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
